theme: jekyll-theme-cayman
title: Microsoft365.com/setup || Microsoft365/setup
description: Install office 365 on your windows or mac device using the steps given here at Micros0ft365.com/setup. Enter office 365 product key and activate your account. 
webmaster_verifications:
